### ISSUE TITLE
Color button bug

### ISSUE THREAD

**Issue by Anakharsis9** [RayDarar/Projects-Summer-2019#3]
I tried to make the button colored, but after its border radius changed, it lost color and errors occurred.
`      Button element = new Button();
        element.setMinHeight(100);
        element.setMinWidth(100);
        //element.setStyle("-fx-background-color : violet"); `

**Comment by RayDarar** [comment]
I reviewed my code.

In changeBorder() method, there's 2 conditions for checking whether border radius and background radius are in style text of the given element or not.
And after some "value" manipulations, I just replace old styles by new, so there shouldn't be any errors.

**Comment by RayDarar** [comment]
Oh, found mistake.

Problem is, every style property must end with ';' sign.
And as you can see, your background color property do not have semicolon at the end :D

**Comment by RayDarar** [comment]
I see 2 ways of solving this.

1) You fix your code for semicolon endings.
2) I'm writing additional logic for styles checking.

What path to chose, It's up 2 you
